[WebAPP]
title = "Go Connection Server"
env = "DEV"
port = "8020"
domain="localhost"
app="goconn"
expires=86400


[MasterMDB]
addrs = ["localhost:27017"]
database = "lemocar"
username = "lemocar"
password = "LM3fsKjsd9083JUB4dfhas4susUH7937"
timeout = 50
poollimit = 10

[CommonCache]
addr = "127.0.0.1:6379"
db = 0
timeout = 5
password = ""


[Log]
disable_stdout=false
filename="log/goconn.log"
max_size=1
max_age=90
max_backups=10
disable_debug_level=true

[MongoDB]
ip = "localhost"
port = 27017
database = "lemocar"
username = "lemocar"
password = "LM3fsKjsd9083JUB4dfhas4susUH7937"
timeout = 50
poollimit = 10